### PR TITLE
Added support python 3.9

### PR DESCRIPTION
**Pull request by ermakov-oleg**
Resolves issue #22

### CODE REVIEW

**Comment by ermakov-oleg** [comment]
@googlebot I signed it!

**Comment by mctavish** [comment]
Thanks for the pull request!  Unfortunately I'm not able to merge it directly; our build & release pipeline relies on a source of truth other than this github repo.  What I'll do is take this set of changes, apply them to the "true" codebase (along with updating our tests) and then get this into a release asap.

Thanks again, and sorry that this isn't as direct as it could be.

**Comment by jturmel** [comment]
Thank you for the update, this is still holding us up from upgrading our App Engine runtimes to Python 3.9 since we rely on debugger support.

**Comment by mctavish** [comment]
This PR has been modified and committed as https://github.com/GoogleCloudPlatform/cloud-debug-python/commit/67e3b8c3dede37ca39fd495dc1e042b3a8044631

Thanks again for the contribution; I'll close this PR now.

**Pull request closed without merging**
